### ISSUE TITLE
Crash mod

### ISSUE THREAD

**Issue by MineCinema** [KatatsumuriPan/BetterWaterMesh#2]
Time: 2024-10-24 01:21:03 MSK
Description: Initializing game

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Better Water Mesh (b_water_mesh)
Caused by: net.minecraftforge.fml.relauncher.ReflectionHelper$UnableToAccessFieldException: net.minecraftforge.fml.relauncher.ReflectionHelper$UnableToFindFieldException: java.lang.NoSuchFieldException: field_175025_e
    at net.minecraftforge.fml.relauncher.ReflectionHelper.setPrivateValue(ReflectionHelper.java:251)
    at kpan.b_water_mesh.util.ReflectionUtil.setObfPrivateValue(ReflectionUtil.java:206)
    at kpan.b_water_mesh.util.ReflectionUtil.setObfPrivateValue(ReflectionUtil.java:198)
    at kpan.b_water_mesh.ModMain.postInit(ModMain.java:47)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    
    
 Specifically, the error indicates the inability to find a field named field_175025_e, which is most likely an obfuscated name.
What's the problem:
The field named field_175025_e has either been changed or is completely missing from the current version of Minecraft or Forge.
The mod tries to access the field using ReflectionHelper, but the field is not found, which causes an exception.
Decisions:
Check the SRG field name:

Obfuscated field names can change between Minecraft versions. The field_175025_e field could have been renamed.
Find the current SRG name of this field for your version of Minecraft.

**Comment by KatatsumuriPan** [comment]
Can you run Minecraft without any other mods except Better Water Mesh?
